# Generated by Django 4.2.20 on 2025-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoplate',
            name='region',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoplate',
            name='region_int',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
