# Generated by Django 4.2.20 on 2025-03-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_autoplate_region_autoplate_region_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoplate',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
